### ISSUE TITLE
inconsistent name parsing in JSON-LD conversion

### ISSUE THREAD

**Issue by augustfly** [datacite/bolognese#16]
Consider the following pair of `<creators>` blocks:

    <creator>
        <creatorName>Mahdi D.</creatorName>
        <nameIdentifier schemeURI="http://orcid.org/" nameIdentifierScheme="ORCID">0000-0001-5000-0007</nameIdentifier>
    </creator>
    <creator>
        <creatorName>Soubiran C.</creatorName>
    </creator>
    <creator>
        <creatorName>lanco-Cuaresma S.</creatorName>
    </creator>
    <creator>
        <creatorName>Chemin L.</creatorName>
    </creator>

and 

    <creator>
        <creatorName>D. Mahdi</creatorName>
        <nameIdentifier schemeURI="http://orcid.org/" nameIdentifierScheme="ORCID">0000-0001-5000-0007</nameIdentifier>
    </creator>
    <creator>
        <creatorName>C. Soubiran</creatorName>
    </creator>
    <creator>
        <creatorName>S. Blanco-Cuaresma</creatorName>
    </creator>
    <creator>
        <creatorName>L. Chemin</creatorName>
    </creator>

for the first block the `bolognese` export of JSON-LD with the given/surname parser works for all authors like magic. For the latter block it works correctly but only for the first `<creator>` then doesn't run for subsequent entries.  This seems like a bug. 

The full XML of the first entry is attached in this zip file:  [test.zip](https://github.com/datacite/bolognese/files/1081093/test.zip)
To be clear it is all test rather than real data so the DOI prefix is borrowed. 

This was with `bolognese --version == 0.9.22`

**Comment by mfenner** [comment]
This is expected behaviour, as we use a set of rules to determine given names and family name, and they are not perfect. If there is an ORCID ID we know that it is a person, and not an organization, that probably explains the results in the second block.

The solution is to correctly use DataCite metadata, as described in the schema documentation. Ideally using <givenNames> and <familyName>, but at least using the format `last name, given names`.
